### ISSUE TITLE
make message ephemeral

### ISSUE THREAD

**Issue by asterized** [sexnine/discord-cdn-pls#2]
wow fancy new discord feature

**Comment by sexnine** [comment]
@SomeHybrid Ephemeral messages can only be sent as a response to an interaction, therefor it is not possible to send an ephemeral message.  Also, sending a public message also has the benefit of embedding the media using the cdn link if the user is too lazy to edit their message, hence why it also embeds even though it can make the message pretty long.

**Comment by asterized** [comment]
o sad
